fix offset top calculation
jquery/jquery-ui pull request #2057
Opened 2022-03-04 10:23 UTC by SailorMax

in _showDatepicker() we use native input.offsetHeight
but in _checkOffset() we use jquery's input.outerHeight()

jquery's method returns more accurate height for zoomed out pages. In result _checkOffset()'s `offset.top === ( inst.input.offset().top + inputHeight )` never returns true

2022-03-09 16:17 UTC, fnagel commented
Thanks for the report. Does the issue you describe exist when jQuery UI 1.12.1 is used or only with jQuery UI 1.13.0 or newer?

2022-03-09 16:23 UTC, SailorMax commented
the issue exist when jQuery UI 1.12.1 is used also

2022-03-10 15:37 UTC, mgol requested changes
Thanks for the PR. We'll need tests for this change, though. Have a look at existing test in https://github.com/jquery/jquery-ui/tree/main/tests/unit/datepicker to see how to write one.

2022-03-10 15:38 UTC, mgol commented
Also, we'll need you to sign the CLA to proceed.

2022-03-10 15:44 UTC, SailorMax commented
> Also, we'll need you to sign the CLA to proceed.

I'll look later about test. But not ready to sign anything because of 1 tiny patch. You can merge this fix from your name.

2022-03-10 15:53 UTC, mgol commented
I understand your position but we're obliged to require a CLA signature to accept contributions. If you're not willing to sign the CLA then it's better for someone else to look at it so that ownership is clear. Together with tests this would be much larger than just a single line changed.

Given the above, I'm going to close this, sorry!

2022-03-10 15:53 UTC, closed without merging